name: build
on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install .[main] --upgrade pip
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
    - name: Flake
      run: |
        pip install flake8
        flake8
    - name: Install dependencies
      run: pip install wheel twine
    - name: Publish package distribution to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload --skip-existing dist/*
